# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC01(self):
    self.driver.get("https://crypto-tracker.swapnilg4u.repl.co/")
    self.driver.set_window_size(1050, 660)
    self.driver.find_element(By.ID, "myInput").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container:nth-child(1)").click()
    assert self.driver.title == "Real Time Cryto Tracking"
    self.driver.find_element(By.ID, "myInput").click()
    self.driver.close()
  
