# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC05():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC05(self):
    self.driver.get("https://crypto-tracker.swapnilg4u.repl.co/")
    self.driver.set_window_size(1051, 660)
    self.driver.find_element(By.CSS_SELECTOR, ".container:nth-child(1)").click()
    assert self.driver.title == "Real Time Cryto Tracking"
    self.driver.find_element(By.ID, "myInput").click()
    element = self.driver.find_element(By.ID, "myInput")
    assert element.is_enabled() is True
    self.driver.find_element(By.ID, "myInput").click()
    self.driver.find_element(By.ID, "myInput").send_keys("1INCH")
    self.driver.find_element(By.ID, "myInput").send_keys(Keys.ENTER)
    elements = self.driver.find_elements(By.LINK_TEXT, "1INCH")
    assert len(elements) > 0
    element = self.driver.find_element(By.CSS_SELECTOR, ".card-footer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".card-footer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".card-footer")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".card-footer").click()
    self.driver.close()
  
