<?php

print "<!DOCTYPE html>\n";
print "<html>\n";
print "  <head>\n";
print "    <meta charset=\"utf-8\">\n";
print "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "    <title>Crypto Currency</title>\n";
print "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "    <!-- Font awesome icon -->\n";
print "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\" integrity=\"sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==\" crossorigin=\"anonymous\" />\n";
print "    <link rel=\"stylesheet\" href=\"user.css\">\n";
print "  </head>\n";
print "  <body>\n";
print "\n";
print "<!-- header -->\n";
print "<header>\n";
print "    <nav class = \"navbar\">\n";
print "      <div class = \"container\">\n";
print "        <a href = \"Aboutcrpy.html\" class = \"navbar-brand\">Crypto Currency</a>\n";
print "        <div class = \"navbar-nav\">\n";
print "          <a href = \"https://crypto-tracker.swapnilg4u.repl.co/\">Search</a>\n";
print "          <a href = \"user.html\">User</a>\n";
print "        </div>\n";
print "      </div>\n";
print "    </nav>\n";
print "    <!-- blog -->\n";
print "    <section class = \"blog\" id = \"blog\">\n";
print "        <div class = \"container\">\n";
print "          <div class = \"title\">\n";
print "            <h2>About Yourself</h2>\n";
print "            <p>Price is what you pay. Value is what you get.</p>\n";
print "          </div>\n";
print "          <div class = \"blog-content\">\n";
print "            <!-- item -->\n";
print "            \n";
print "              <div class = \"blog-text\">\n";
print "                <h3>NAME </h3><p>User name</p>\n";
print "                <h3>EMAIL ID </h3><p>User EmailId</p>\n";
print "                <h3>CONTACT NO. </h3><p>User Contact Number</p>\n";
print "              </div>\n";
print "            </div>\n";
print "            <!-- end of item -->\n";
print "          </div>\n";
print "        </div>\n";
print "      </section>\n";
print "      <!-- end of blog -->\n";
print "  </header>\n";
print "  <!-- end of header -->\n";
print "\n";
print "    <!-- footer -->\n";
print "    <footer>\n";
print "        <div class = \"social-links\">\n";
print "          <a href = \"#\"><i class = \"fab fa-facebook-f\"></i></a>\n";
print "          <a href = \"#\"><i class = \"fab fa-twitter\"></i></a>\n";
print "          <a href = \"#\"><i class = \"fab fa-instagram\"></i></a>\n";
print "          <a href = \"#\"><i class = \"fab fa-pinterest\"></i></a>\n";
print "        </div>\n";
print "        <span>INVEST & EARN</span>\n";
print "      </footer>\n";
print "      <!-- end of footer -->\n";
print "    \n";
print "    \n";
print "  </body>\n";
print "</html>";

?>
